"""
This monstrosity of a script was created to enable webhooks across all the Signrequest teams
at Infinit-O Manila.

Context:
The Signrequest API has an `events/` endpoint that produces a stream of "events" that occur whenever
specific actions are taken on the Signrequest platform - things like when documents are
created, sent, signed, rejected, etc.

However, these events are not automatically generated by the Signrequest platform. They require that
a webhook be enabled in order to see them.

Webhooks each cover only a single type of event and must be enabled one-at-a-time because there is
no unified web interface that covers the whole organization.

Solution:
This script is designed to take in a JSON file containing credentials and URLs for each of the teams
here at IOM, and send POST requests en-masse to enable webhooks for each of the teams, such that
a rich event stream is generated for each of them.

There are 10 teams at IOM that use Signrequest and have URLs.

There are 7 event types we need to watch. They are as follows:
["sending_error", "sent" ,"declined", "cancelled", "signed", "signer_signed", "signer_email_bounced"]

A total of 70 post requests need to be sent to enable webhooks for all teams, and all types.
"""
import argparse
import json

import requests

ap = argparse.ArgumentParser()
ap.add_argument("credfile", help="relative path to the credentials file.")
ap.add_argument("outfile", help="relative path to where you want the output file stored.")

args = ap.parse_args()

if __name__ == "__main__":
    with open(args.credfile, "r") as F:
        cred_data: list[dict] = json.loads(F.read())

    # NOTE: LOGIC GOES HERE

    with open(args.outfile, "r") as F:
        pass
